-- ============================================================
-- POPIS
-- ============================================================

-- loupenicka → place_loupenicka
-- mistecka → country_mistecka → area_mistecka → place_mistecka

-- Používám:
-- ON DELETE CASCADE na child tabulkách, aby se podřízená data smazala automaticky s parentem,
-- složené UNIQUE constraints pro slugy v rámci parent entity,
-- CHECK s regexem pro gps_coords, protože PostgreSQL regex v constraints podporuje.


-- ============================================================
-- RESET
-- ============================================================

DROP TABLE IF EXISTS place_mistecka CASCADE;
DROP TABLE IF EXISTS area_mistecka CASCADE;
DROP TABLE IF EXISTS country_mistecka CASCADE;
DROP TABLE IF EXISTS mistecka CASCADE;

DROP TABLE IF EXISTS place_loupenicka CASCADE;
DROP TABLE IF EXISTS area_loupenicka CASCADE;
DROP TABLE IF EXISTS loupenicka CASCADE;


-- ============================================================
-- LOUPENICKA
-- ============================================================

CREATE TABLE loupenicka (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    slug        TEXT NOT NULL UNIQUE,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE place_loupenicka (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loupenicka_id  BIGINT NOT NULL REFERENCES loupenicka(id) ON DELETE CASCADE,
    name           TEXT NOT NULL,
    type           TEXT,
    description    TEXT,
    gps_coords     TEXT CHECK (
        gps_coords IS NULL OR (
            gps_coords ~ '^[0-9]{1,2}(\.[0-9]+)?[NS], [0-9]{1,3}(\.[0-9]+)?[EW]$'
            OR
            gps_coords ~ '^-?([0-8]?[0-9]|90)(\.[0-9]+)?, -?([0-9]{1,2}|1[0-7][0-9]|180)(\.[0-9]+)?$'
        )
    ),
    large_image_url     TEXT NOT NULL,
    small_image_url     TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- MISTECKA
-- ============================================================

CREATE TABLE mistecka (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    slug        TEXT NOT NULL UNIQUE,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE country_mistecka (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mistecka_id  BIGINT NOT NULL REFERENCES mistecka(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    slug         TEXT NOT NULL,
    code         TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT country_mistecka_slug_unique_per_mistecka
        UNIQUE (mistecka_id, slug),

    CONSTRAINT country_mistecka_code_not_empty
        CHECK (char_length(trim(code)) > 0)
);

CREATE TABLE area_mistecka (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mistecka_id         BIGINT NOT NULL REFERENCES mistecka(id) ON DELETE CASCADE,
    country_mistecka_id BIGINT NOT NULL REFERENCES country_mistecka(id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    slug                TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT area_mistecka_slug_unique_per_country
        UNIQUE (country_mistecka_id, slug)
);

CREATE TABLE place_mistecka (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mistecka_id         BIGINT NOT NULL REFERENCES mistecka(id) ON DELETE CASCADE,
    country_mistecka_id BIGINT NOT NULL REFERENCES country_mistecka(id) ON DELETE CASCADE,
    area_mistecka_id    BIGINT NOT NULL REFERENCES area_mistecka(id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    type                TEXT,
    description         TEXT,
    gps_coords          TEXT CHECK (
        gps_coords IS NULL OR (
            gps_coords ~ '^[0-9]{1,2}(\.[0-9]+)?[NS], [0-9]{1,3}(\.[0-9]+)?[EW]$'
            OR
            gps_coords ~ '^-?([0-8]?[0-9]|90)(\.[0-9]+)?, -?([0-9]{1,2}|1[0-7][0-9]|180)(\.[0-9]+)?$'
        )
    ),
    large_image_url     TEXT NOT NULL,
    small_image_url     TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- INDEXY
-- ============================================================

CREATE INDEX idx_place_loupenicka_loupenicka_id
    ON place_loupenicka (loupenicka_id);

CREATE INDEX idx_country_mistecka_mistecka_id
    ON country_mistecka (mistecka_id);

CREATE INDEX idx_area_mistecka_mistecka_id
    ON area_mistecka (mistecka_id);

CREATE INDEX idx_area_mistecka_country_mistecka_id
    ON area_mistecka (country_mistecka_id);

CREATE INDEX idx_place_mistecka_mistecka_id
    ON place_mistecka (mistecka_id);

CREATE INDEX idx_place_mistecka_country_mistecka_id
    ON place_mistecka (country_mistecka_id);

CREATE INDEX idx_place_mistecka_area_mistecka_id
    ON place_mistecka (area_mistecka_id);


-- ============================================================
-- SHARED PLACES
-- ============================================================

CREATE TABLE shared_places (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kind                TEXT NOT NULL CHECK (kind IN ('loupenicka', 'mistecka')),
    place_loupenicka_id BIGINT REFERENCES place_loupenicka(id) ON DELETE CASCADE,
    place_mistecka_id   BIGINT REFERENCES place_mistecka(id) ON DELETE CASCADE,
    expires_at          TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '72 hours',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT check_single_place CHECK (
        (kind = 'loupenicka' AND place_loupenicka_id IS NOT NULL AND place_mistecka_id IS NULL) OR
        (kind = 'mistecka' AND place_mistecka_id IS NOT NULL AND place_loupenicka_id IS NULL)
    )
);

CREATE INDEX idx_shared_places_expires_at ON shared_places (expires_at);